stackblitz/tutorialkit

.github/workflows/ci.yaml
This PR updates the `main` workflow to `ci` cause `main` isn't very descriptive. I noticed this when I wanted to set up required status checks.
This aligns with what other OSS projects do as well, e.g., [vite](https://github.com/vitejs/vite/blob/main/.github/workflows/ci.yml).
=> chore: rename github workflow

packages/template/.vscode/extensions.json
As the [documentation](https://tutorialkit.dev/guides/installation/#editor-configuration) recommends using the [MDX extension](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx), I have added it to the recommendations section in the extensions.json file of the template.
=> feat: add MDX extension to `recommendations` in extensions.json

.changeset/smooth-camels-fail.md, packages/astro/src/default/utils/nav.ts
I discovered a bug where parts, chapters, and lessons in navList were being sorted by comparing numbers as strings, causing issues like Chapter 10 being placed before Chapter 2.
Reproduction: https://stackblitz.com/~/github.com/morinokami/tutorialkit-sort-problem
I have fixed this by comparing each key as a numeric value in the objectToSortedArray function.
=> fix: sort navigation items numerically in `objectToSortedArray` function

.changeset/fast-socks-cough.md, packages/cli/src/commands/create/dependencies.ts
Currently, when creating a project using a command like `npm create tutorial`, the default package manager for installing dependencies is [hardcoded to pnpm](https://github.com/stackblitz/tutorialkit/blob/94546823c3393e4d3005ff78038119692475466b/packages/cli/src/commands/create/dependencies.ts#L81). However, it seems more intuitive to use the package manager that was used to run the create command as the default. This PR makes that change. Additionally, if the package manager cannot be determined, the fallback default is set to npm.
=> feat: set default package manager to the one used with `create` command

.changeset/angry-man-yells.md, packages/components/react/package.json, packages/components/react/src/CodeMirrorEditor/languages.ts, pnpm-lock.yaml
Adds support for the wat language via [@codemirror/lang-wast](https://github.com/codemirror/lang-wast) ([context](https://x.com/elmd_/status/1800053726075310249))
We may want to explore exposing support for users to add their own lezer grammars and language servers. In the case of, perhaps a custom language, we might not want to merge it into the package directly but still want to allow support without monkey-patching the package.
=> feat: add lezer support for wast via codemirror wast package

packages/runtime/src/store/index.ts, packages/runtime/src/tutorial-runner.ts
This PR fixes an error at runtime where React complains about an hydration mismatch between what was rendered on the server vs on the client.
This is because during SSR, we do not set the initial commands and thus the `steps` are empty while on the client they are set sooner. I wouldn't have expected that to be the case but the easier here is to just split `runCommands` in two functions:
* `setCommands` which is similar to `setPreviews` and `setTerminalConfiguration`.
* `runCommands` which interact with WebContainer
The error fixed by this PR:
=> fix: hydration error after runtime refactor

packages/astro/src/webcontainer-files.ts
This PR makes sure that `.DS_Store` and `*.swp` files (from vim) are never added to WebContainer.
If there are any other widely known files from editors or OS that could also accidentally end up in WebContainer, we should add them to that list.
=> fix: ignore platform specific files

packages/components/react/src/Nav.tsx
While using TutorialKit, I noticed that the navigation was not always on top of the content.
Before:
After:
=> fix(nav): make sure nav is on top of the content

packages/components/react/src/Panels/EditorPanel.tsx, packages/components/react/src/Panels/TerminalPanel.tsx, packages/components/react/src/Terminal/index.tsx, packages/runtime/src/store/editor.ts, packages/runtime/src/store/index.ts
This PR fixes an issue where `store.updateFile()` didn't reflect the new content in the editor.
It also adds a new method to the store called `onDocumentChanged()` which you can use to subscribe to changed to a document. This allows you to do clever things in a custom component like listening to the changes of a `css` file and dynamically injecting that into the page.
=> feat(store): fix current document and add onDocumentChanged

CHANGELOG.md, package.json, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/cli/package.json, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/create-tutorial/CHANGELOG.md, packages/create-tutorial/package.json, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/types/package.json, pnpm-lock.yaml, scripts/changelog.mjs
This PR introduces `conventional-changelog` to update automatically the `CHANGELOG.md` file based on the git history.
To create a new version in the changelog, one must do:
1. Update the `version` field in every package
2. Run `pnpm changelog`
3. Check the update to `CHANGELOG.md` and add shoutouts for our awesome external contributors :partying_face: 
4. Open a PR
5. When the PR is merged and the package is published, update a new tag with:
```bash
git tag -a $VERSION $COMMIT_HASH -m "TutorialKit $VERSION"
git push --tags
```
=> chore: bump version and add CHANGELOG.md

packages/components/react/src/CodeMirrorEditor/cm-theme.ts, packages/components/react/src/styles/cm.css
While documenting the editor, I found some things that couldn't be styled. And I also renamed a couple. I'll comment inline.
=> fix(theme): fix some styling for the editor

packages/components/react/src/CodeMirrorEditor/index.tsx
This PR fixes a bug reported by @SamVerschueren where the editor sometimes remove a changes that was just made.
It's caused by the debounce which delay when the document is updated. However, the document might also be updated in the meantime by something else: here the scroll.
When the scroll position changes, the `document` will be updated which then cause the `useEffect` hook which calls `setEditorDocument` to be called and it would then think that the document has changed given the editor state content and the document content are different. So it resets the cursor to the beginning which is incorrect. With this PR, we ignore external scroll position changes as they are expected to be entirely controlled by the editor.
Note that there still could be a bug if an external component was …
=> fix: editor ignoring changes

packages/runtime/src/store/index.ts
fix for https://github.com/stackblitz/tutorialkit/issues/107 In the hasSolution function of TutorialStore, `this._lessons.solution` is an array with the structure [lessonName, [list of solution files]]. Instead of checking the length of the solution array. we have to check the length of the second index which is the list of solution files.
=> fix: problem with creating lessons without solution files

docs/tutorialkit.dev/astro.config.ts
This will add the social links to the top of [tutorialkit.dev](https://tutorialkit.dev).
I also linked X and Discord. Do we want that, because it just links to StackBlitz instead of something TutorialKit specific? @sulco
=> docs: add social links

scripts/changelog.mjs, scripts/changelog/Package.mjs, scripts/changelog/generate.mjs
This PR fix the changelog generation so that it when we do `pnpm changelog` it generate the changelog for every packages, in particular the CLI. The previous release PR didn't had the changelog for the CLI because we are bumping the CLI at a later point.
=> fix: generate correct changelogs when doing a PR

.github/workflows/prepare-release.yaml, .github/workflows/publish-release.yaml
Tiny update to the PR description for the release PR. Noticed there was punctuation missing at the end 🙈.
=> chore: update release workflow

.github/actions/setup-and-build/action.yml, .github/workflows/publish-release.yaml, packages/astro/package.json, packages/cli/package.json, packages/components/react/package.json, packages/create-tutorial/package.json, packages/runtime/package.json, packages/theme/package.json, packages/types/package.json
- Scoped packages require `--access public`. It's designed to prevent accidentally publishing scoped packages to public. We do it intentionally for `@tutorialkit/*` packages.
- Github Actions instruct to set `registry` explicitly, though I'm not sure if this is required. 
- > Please note that you need to set the `registry-url` to `https://registry.npmjs.org/` in `setup-node` to properly configure your credentials.
> https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
- `--provenance` flag requires `repository` in `package.json`
Example run which published couple of packages:
- https://github.com/stackblitz/tutorialkit/actions/runs/9854149942/job/27206280839
- https://www.npmjs.com/package/@tutorialkit/runtime
⚠️ Once this is merged, we should immediately …
=> ci(publish): fix publish config

.github/workflows/publish-release.yaml
This PR update the tag updated by the CI to make sure they don't include the `v` prefix. Otherwise this break the changelog generation.
=> fix: tag should be the version without the 'v'

.github/workflows/prepare-release.yaml, .github/workflows/publish-release.yaml
This PR replace the default use of the `GITHUB_TOKEN` with `GITOPS_REPO_PAT` which means that release PRs should now properly trigger workflows.
=> fix(ci): use PAT to make sure release PRs trigger workflows

packages/cli/scripts/build.js
- Disables minifying `tutorialkit` CLI package.
For transparency let's not minify the published CLI package. Seeing code like https://unpkg.com/browse/tutorialkit@0.0.1-alpha.25/dist/index.js doesn't make me eager to run it on my machine. Nowadays it's quite common practice to not minify code that's not going to CDN.
=> build(cli): disable minifying

.github/workflows/publish-create-tutorial.yaml, .github/workflows/publish-release.yaml, packages/create-tutorial/package.json, pnpm-lock.yaml
Separates `create-tutorial` package releasing from all other `@tutorialkit/*` and `tutorialkit` packages. The `create-tutorial` is essentially only an alias for installing `tutorialkit` package and calling it. I don't think we'll be publishing many versions of this package. 
- Added workflow for separately specifying version for `create-tutorial` and publishing it
- Defined `create-tutorial` package's dependency on `tutorialkit` as `latest`, so that package managers will always install the latest version of it.
Example:
- Manually run the preparation PR workflow: https://github.com/AriPerkkio/tutorialkit/actions/runs/9973462056
- PR is created: https://github.com/AriPerkkio/tutorialkit/pull/36
- Once PR is merged, publish starts automatically: …
=> ci: separate `create-tutorial` releasing

.prettierrc, eslint.config.mjs, package.json, pnpm-lock.yaml
- Include `*.astro` files in linting
- Fix prettier config
Note that target branch is base of #152, not `main`.
=> chore: lint `*.astro` files

.prettierrc, docs/tutorialkit.dev/src/components/Layout/Head.astro, docs/tutorialkit.dev/tsconfig.json, eslint.config.mjs, extensions/vscode/build.mjs, extensions/vscode/src/commands/index.ts, extensions/vscode/src/commands/tutorialkit.initialize.ts, extensions/vscode/src/commands/tutorialkit.load-tutorial.ts, extensions/vscode/src/commands/tutorialkit.select-tutorial.ts, extensions/vscode/src/utils/isTutorialKit.ts, extensions/vscode/src/views/lessonsTree.ts, package.json, pnpm-lock.yaml
Small PR that updates some minor code styling to streamline consistency with the rest of the repo.
=> chore(style): minor code style adjustments for improved consistency

.github/workflows/prepare-release.yaml, .github/workflows/publish-release.yaml
- Adds `token` to `create-pull-request` workflow so that CI workflows start automatically when bot creates the PR
- Tested here https://github.com/stackblitz/tutorialkit/pull/160
=> ci: use PAT on `create-pull-request`

docs/demo/package.json, docs/tutorialkit.dev/package.json, packages/astro/package.json, packages/template/package.json, pnpm-lock.yaml
- Fixes https://github.com/stackblitz/tutorialkit/issues/157
Astro v4.12.0 includes fix for #157. https://github.com/withastro/astro/releases/tag/astro%404.12.0
=> fix(deps): update `astro` for Node 18.18 compatibility

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump `@tutorialkit` packages to version 0.0.3 and generate changelogs.
=> chore: release `@tutorialkit` packages v0.0.3

docs/demo/src/content/config.ts, packages/template/src/content/config.ts, packages/types/src/schemas/content.spec.ts, packages/types/src/schemas/content.ts, packages/types/src/schemas/index.ts
- Adds `contentSchema` to avoid leaking implementation details of final schema to tutorials
=> feat: add `contentSchema`

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/create-tutorial/CHANGELOG.md, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump `@tutorialkit` packages to version 0.1.0 and generate changelogs.
=> chore: release `@tutorialkit` packages v0.1.0

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
We want to release the extension update that includes the frontmatter autocompletion.
=> chore: release TutorialKit vscode extension v0.1.0

packages/template/uno.config.ts
- Fixes https://github.com/stackblitz/tutorialkit/issues/182
- Fixes https://github.com/stackblitz/tutorialkit/issues/183
- Ref. https://github.com/mrmlnc/fast-glob/issues/452
=> fix(cli): normalize windows paths for `fast-glob`

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx
- Fixes broken metadata. When copying the example to existing project validation fails
=> docs: fix metadata

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/create-tutorial/CHANGELOG.md, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump `@tutorialkit` packages to version 0.1.1 and generate changelogs.
=> chore: release `@tutorialkit` packages v0.1.1

packages/astro/src/webcontainer-files/constants.ts
- Fixes https://github.com/stackblitz/tutorialkit/issues/189
Fixes issues where users would see `jsh: permission denied` errors if `src/templates/*/node_modules` were present on host machines' file system. TutorialKit would copy those `node_modules` to webcontainers and try to run them. These `node_modules` may contain platform specific binaries that fail to run on webcontainers (non-wasm builds). 
Adds `node_modules` to be ignored in `src/templates`. At this point the change is hard-coded and not configurable. See https://github.com/stackblitz/tutorialkit/issues/189#issuecomment-2262036287.
I'll create a follow-up feature request that would allow including `node_modules`, so that tutorial authors could include pre-optimized dependencies in their templates. This is lower priority task …
=> fix: ignore templates `node_modules`

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/create-tutorial/CHANGELOG.md, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump `@tutorialkit` packages to version 0.1.2 and generate changelogs.
=> chore: release `@tutorialkit` packages v0.1.2

.github/workflows/prepare-release.yaml, .github/workflows/publish-release.yaml, CONTRIBUTING.md, README.md, extensions/vscode/package.json, extensions/vscode/scripts/build.mjs, package.json, packages/cli/package.json, packages/create-tutorial/package.json, pnpm-lock.yaml, scripts/publish.sh
- Renames npm package `tutorialkit` to `@tutorialkit/cli`
- Adds some documentation to `CONTRIBUTING.md` about package naming convention. This is mostly related to development time communication practices and doesn't affect end users.
- Renames (internally) `tutorialkit-vscode` to `tutorialkit`. Removes work-around from build script that was used to do this renaming right before publishing. This name is already used by the published extension. 
BREAKING CHANGES:
- `tutorialkit` npm package is now unused. We should probably deprecate that from npm? Or just leave it as is. 
- Adds new package `@tutorialkit/cli`. This package does not yet exist in npm. I'm not sure if publishing this package will work without any permission settings. Do we need to add https://www.npmjs.com/~stackblitz-devops …
=> feat!: rename `tutorialkit` to `@tutorialkit/cli`

.github/workflows/integration-test-cli.yaml, packages/cli/package.json
=> chore: release CLI v0.1.3

.github/workflows/ci.yaml, packages/astro/src/default/utils/content.ts, packages/astro/src/default/utils/content/files-ref.spec.ts, packages/astro/src/default/utils/content/files-ref.ts, packages/astro/test/fixtures/files/first.js, packages/astro/test/fixtures/files/nested/directory/second.ts, packages/cli/tests/__snapshots__/create-tutorial.test.ts.snap, packages/cli/tests/create-tutorial.test.ts
- Fixes https://github.com/stackblitz/tutorialkit/issues/209
=> fix(astro): sub folders not working on Windows

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, packages/astro/src/default/utils/content/default-localization.ts, packages/types/src/schemas/i18n.ts
- Link should be in plural instead
- Ref. https://github.com/stackblitz/tutorialkit/pull/202#discussion_r1700841915
=> fix(astro): webcontainers link to be in plural

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
In order to release the changes made the vscode extension we needed to update the changelog. This PR fixes that.
=> chore: prepare extension changelog for 0.1.1

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, packages/runtime/src/store/previews.spec.ts, packages/runtime/src/store/previews.ts, packages/runtime/src/webcontainer/port-info.ts, packages/runtime/src/webcontainer/preview-info.spec.ts, packages/runtime/src/webcontainer/preview-info.ts, packages/template/src/content/tutorial/1-basics/1-introduction/2-foo/content.mdx, packages/template/src/templates/default/src/index.js, packages/types/src/schemas/common.ts
- Closes https://github.com/stackblitz/tutorialkit/issues/192
Adds support for defining pathname for previews. Example from Vite Plugin Tutorial where I'd like to show two previews for same server:
```yaml
---
type: lesson
title: Extra - Source map support
focus: /vite.config.ts
previews:
- { port: 5173, title: "Vite" }
- { port: 5173, title: "Inspect", pathname: "/__inspect/" }
---
```
This will also be useful for remult tutorial: https://learn.remult.dev/1-basics/5-live-query/2-realtime-updates - mentioned here https://github.com/stackblitz/tutorialkit/discussions/226
=> feat(runtime): add `preview.pathname`

packages/astro/src/default/components/WorkspacePanelWrapper.tsx, packages/components/react/src/Panels/PreviewPanel.tsx, packages/components/react/src/core/Terminal/index.tsx
Fixes React's state warning that happen when navigating between pages. `setLesson` that's done inside rendering block attempts to update state of the components that are just about to unmount.
```
Warning: Cannot update a component (`PreviewPanel`) while rendering a different component (`WorkspacePanelWrapper`). To locate the bad setState() call inside `WorkspacePanelWrapper`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
at WorkspacePanelWrapper (http://localhost:4321/@fs/Users/x/tutorialkit/packages/astro/dist/default/components/WorkspacePanelWrapper.tsx:23:41)
printWarning                        @    react-dom.development.js:86
error                               @    react-dom.development.js:60
warnAboutRenderPhaseUpdatesInDEV    @ …
```
=> fix(astro): don't modify state during re-renders of `<WorkspacePanelWrapper />`

extensions/vscode/src/language-server/index.ts, extensions/vscode/src/language-server/languagePlugin.ts
This PR makes sure that the autocompletion and validation for the frontmatter applies primarily to files that should be within a tutorialkit project. The heuristic used is very simple and not perfect so there could still be false positive. However, after this PR it will become very unlikely as one would need to create a markdown file named `meta.md` or `content.md(x)` under a `src/content/tutorial` path.
Note that files under `_files` and `_solution` are ignored as this could be a common situation where the extension would incorrectly perform validation and provide autocompletions.
Closes #237
=> fix(extension): only match tutorialkit content and meta files

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/components/react/CHANGELOG.md, packages/components/react/package.json, packages/create-tutorial/CHANGELOG.md, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump core packages to version 0.1.5 and generate changelogs.
=> chore: release core packages v0.1.5

packages/create-tutorial/src/index.ts
Rename `tutorialkit` to `@tutorialkit/cli` missing in #153.
The PR #153 has been renamed the `@tutorialkit/cli` dependency in `package.json`, but no changed in `index.ts`, if now running locally will see the error: `Error: Cannot find module 'tutorialkit'`, so this PR is fixed this.
=> fix(cli): `create-tutorial` not depending on `@tutorialkit/cli` package

packages/components/react/package.json, packages/components/react/src/core/CodeMirrorEditor/languages.ts, pnpm-lock.yaml
Add Vue language ([`@codemirror/lang-vue`](https://github.com/codemirror/lang-vue)) into [CodeMirrorEditor/languages.ts](https://github.com/stackblitz/tutorialkit/blob/main/packages/components/react/src/core/CodeMirrorEditor/languages.ts).
=> feat: add Vue language to CodeMirror

packages/astro/types.d.ts
This PR fixes the type of `webcontainer` in `@tutorialkit/astro/types` to be `Promise<WebContainer>` and not `WebContainer`.
=> fix(astro/types): `webcontainer` should be a `Promise<WebContainer>`

.github/workflows/publish-create-tutorial.yaml, packages/cli/tests/create-tutorial.test.ts
- Fixes https://github.com/stackblitz/tutorialkit/pull/260#issuecomment-2295780181
- Ref. https://github.com/stackblitz/tutorialkit/pull/145
=> test: bump version of pinned `@astrojs/language-server`

packages/create-tutorial/package.json
Bump `create-tutorial` to version 0.0.3.
=> chore: release `create-tutorial` v0.0.3

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, packages/components/react/src/Panels/TerminalPanel.tsx, packages/components/react/src/Panels/WorkspacePanel.tsx, packages/components/react/src/core/Terminal/index.tsx, packages/runtime/src/webcontainer/terminal-config.ts, packages/types/src/schemas/common.ts, test/ui/src/content/tutorial/tests/terminal/default/content.md, test/ui/src/content/tutorial/tests/terminal/meta.md, test/ui/src/content/tutorial/tests/terminal/open-by-default/content.md, test/ui/test/terminal.test.ts
- Closes https://github.com/stackblitz/tutorialkit/issues/132
- Example usage https://github.com/AriPerkkio/tutorial-vite-plugin/pull/19
- Adds also test cases that won't be run before https://github.com/stackblitz/tutorialkit/pull/241 is merged
Adds new `terminal.open` option that can be used to set terminal open by default for specific lesson.
```yaml
---
type: lesson
title: Default
terminal:
open: true       # <-- Terminal will be open when page is navigated to
panels: terminal
---
```
=> feat(runtime): option for setting terminal open by default

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, packages/astro/src/default/utils/content/default-localization.ts, packages/components/react/src/Panels/PreviewPanel.tsx, packages/types/src/schemas/i18n.ts
I'm currently using the tutorialkit version v0.1.5, if added some i18n texts:
*docs/demo/src/content/tutorial/meta.md*
```md
---
type: tutorial
mainCommand: ['npm run dev', 'Starting http server']
prepareCommands:
- ['npm install', 'Installing dependencies']
i18n:
prepareEnvironmentTitleText: '啟動環境'
previewTitleText: '預覽'
toggleTerminalButtonText: '切換終端機'
---
```
The i18n will work on webcontainer starting:
But not working on webcontainer started:
* Add missing `Toggle Terminal` i18n text in started `<Preview>`
* Add missing `Preview` i18n text
=> fix: missing preview i18n

packages/components/react/src/Panels/EditorPanel.tsx, packages/components/react/src/Panels/WorkspacePanel.tsx
- Split from https://github.com/stackblitz/tutorialkit/pull/241
If Solve-button is clicked quickly enough, it does not reveal the solution files. It does change the button text to "Reset" which is not true in that case.
https://github.com/stackblitz/tutorialkit/blob/095ed570702d1b8de9370565b94103cd0740c408/packages/runtime/src/store/index.ts#L290-L295
=> fix(react): solve-button not working before lesson loads

packages/components/react/src/Panels/PreviewPanel.tsx, packages/components/react/src/core/CodeMirrorEditor/index.tsx
- Split from https://github.com/stackblitz/tutorialkit/pull/241
Adds accessible names for editor and preview so that users with assistive technologies can identify the elements.
=> fix(react): editor and preview missing accessible names

packages/components/react/src/core/FileTree.tsx
- Split from https://github.com/stackblitz/tutorialkit/pull/241
Adds attribute to file element's `button`'s so that it can be seen which file is currently selected/active.
=> fix(react): file tree's files to indicate selected state

packages/astro/tsconfig.json, packages/components/react/tsconfig.build.json, packages/components/react/tsconfig.json, packages/runtime/tsconfig.build.json, packages/runtime/tsconfig.json
Looking at the package, everything seemed like it should not include the spec files. After some investigation I found some strange behavior with the components package being included in the build 🤔. 
Package does not respect the `tsconfig.build.json` when `@tutorialkit/components-react` is included in the `--filter`.
The quick and dirty fix is to just exclude the `@tutorial/components-react` from the filter and have a two step build. It may need further triage with pnpm/typescript. Happy to dig deeper! 
- resolves #158
=> chore: remove spec files from runtime package

.github/workflows/publish-commit.yaml
- Adds https://pkg.pr.new to TutorialKit repo
- All commits pushed to `main` trigger an automatic release
- Maintainers can trigger a release by commenting `/pkg-pr-new` in a PR
This will make testing PRs like https://github.com/stackblitz/tutorialkit/pull/270 a lot easier. In that PR we need to verify that packages are resolved correctly in real environments. Testing such changes by linking packages with `file://` or `link://` protocols in `package.json` doesn't provide good confidence - using real published packages is better.
I've used the workflow from Vite as reference: https://github.com/vitejs/vite/blob/main/.github/workflows/publish-commit.yml
=> ci: setup pkg.pr.new

.github/workflows/publish-commit.yaml
- The `issue_comment` event doesn't happen on given PR so we'll need to checkout to the PR manually
=> ci: checkout to PR branch

docs/tutorialkit.dev/README.md
https://www.tutorialkit.dev (with www) doesn't work
=> docs: tutorialkit.dev link in readme

docs/tutorialkit.dev/src/content/docs/reference/react-components.mdx
- Fixes https://github.com/stackblitz/tutorialkit/issues/287
=> docs: show sources for referenced files

.github/workflows/publish-release.yaml
Deploy documentation only when release is published. 
- https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#set-up-a-workflow
=> ci: deploy docs after release only

docs/demo/package.json, docs/tutorialkit.dev/package.json, e2e/package.json, packages/astro/package.json, packages/astro/src/default/layouts/Layout.astro, packages/template/package.json, pnpm-lock.yaml
With Astro 4.15.0, the experimental support for custom swap functions to be used with Astro's view transitions is no officially exported via the `astro:transitions/client` module.
Closes #235 
I changed the dependency of `astro` to `^4.15.0` in the `package.json` of `packages/astro`.
Wanted to ask first before also updating other package.json files.
=> chore: use swapFunctions from astro:transitions/client

.github/workflows/publish-release.yaml
Let's split documentation publishing into its own step. Other jobs are relying on `publish_release` job to succeed, so if documentation publishing fails for some reason, we don't want to block other jobs.
Also removes `packageManager` which isn't needed/supported.
=> ci: separate job for docs release

packages/astro/src/default/components/TutorialContent.astro
The `Powered by WebContainers` looks a bit weird as it's not aligned to the bottom of the viewport. @sulco & @Nemikolh - any thoughts?
Before:
After:
=> fix: align `Powered by WebContainers` to the bottom

CONTRIBUTING.md
the git@github.com didn't work on my machine
Also - when trying to set this up, it required the specific pnpm@8.15.6 for some reason - so I've added that to the document
=> docs: change the clone url

e2e/src/content/tutorial/tests/navigation/layout-change-from/content.md, e2e/src/content/tutorial/tests/navigation/layout-change-to/content.md, e2e/src/content/tutorial/tests/navigation/meta.md, e2e/test/navigation.test.ts, packages/react/src/Panels/WorkspacePanel.tsx, packages/runtime/src/store/index.ts
- Fixes issues where stale lesson data (metadata) is used after navigating to new lesson
- Deployed at https://github.com/AriPerkkio/tutorial-vite-plugin/pull/24
In https://github.com/stackblitz/tutorialkit/pull/253 the amount of "unnecessary" re-renders were reduced by moving state to components where it was actually needed. 
It turns out, those re-renders were indeed needed as `<WorkspacePanel />` is accessing non-reactive references of the `tutorialStore` instead of reactive ones. This is not easily visible from the code though. We should improve that part later. This is now just a quick fix for the high priority bug.
These are the non-reactive methods of `tutorialStore` that use stale data:
https://github.com/stackblitz/tutorialkit/blob/1eb41fd917ceff08fe9484bd07e732cb673a7a1f/packages …
=> fix(react): stale lesson data after navigation

docs/tutorialkit.dev/astro.config.ts, docs/tutorialkit.dev/src/content/docs/guides/overriding-components.mdx
- Add missing documentation for https://github.com/stackblitz/tutorialkit/pull/112
=> docs: `TopBar` override to mention `open-in-stackblitz-link` slot

docs/tutorialkit.dev/src/components/react-examples/ExampleFileTree.tsx, docs/tutorialkit.dev/src/components/react-examples/ExampleSimpleEditor.tsx, docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, docs/tutorialkit.dev/src/content/docs/reference/react-components.mdx, e2e/src/content/tutorial/tests/file-tree/allow-edits-disabled/_files/first-level/file.js, e2e/src/content/tutorial/tests/file-tree/allow-edits-disabled/_files/first-level/second-level/file.js, e2e/src/content/tutorial/tests/file-tree/allow-edits-disabled/content.md, e2e/src/content/tutorial/tests/file-tree/allow-edits-enabled/_files/first-level/file.js, e2e/src/content/tutorial/tests/file-tree/allow-edits-enabled/_files/first-level/second-level/file.js, e2e/src/content/tutorial/tests/file-tree/allow-edits-enabled/content.md, e2e/src/content/tutorial/tests/file-tree/hidden/_files/example.js, e2e/src/content/tutorial/tests/file-tree/hidden/content.md, e2e/test/file-tree.test.ts, packages/astro/src/default/utils/content/default-localization.ts, packages/react/package.json, packages/react/src/Panels/EditorPanel.tsx, packages/react/src/Panels/WorkspacePanel.tsx, packages/react/src/core/ContextMenu.tsx, packages/react/src/core/FileTree.spec.ts, packages/react/src/core/FileTree.tsx, packages/runtime/src/store/editor.spec.ts, packages/runtime/src/store/editor.ts, packages/runtime/src/store/index.ts, packages/runtime/src/tutorial-runner.ts, packages/runtime/src/webcontainer/editor-config.ts, packages/template/src/content/tutorial/1-basics/1-introduction/2-foo/content.mdx, packages/types/src/entities/index.ts, packages/types/src/schemas/common.ts, packages/types/src/schemas/i18n.ts, pnpm-lock.yaml
- Closes https://github.com/stackblitz/tutorialkit/issues/263
- Related to https://github.com/stackblitz/tutorialkit/discussions/204
- Not related to https://github.com/stackblitz/tutorialkit/issues/208. That one requires WebContainer changes so that we can listen for fs changes.
- While working on the `FileTree` I noticed plenty of issues with it and created https://github.com/stackblitz/tutorialkit/issues/326 as follow-up. 
- Projects that are using `@tutorialkit/react` package directly, **without TutorialKit** need to update `<FileTree>` component's `props.files` type
Adds new metadata option that can be used to enable file and folder creation in the file tree. By default this feature is disabled.
```yaml
---
type: lesson
editor:
fileTree:
allowEdits: true
---
``` …
=> feat: add files via file tree

eslint.config.mjs
This PR makes sure we ignore the `.vscode-test` folder. 
If one start working on the VSCode TutorialKit extension, they will get that folder and our current `pnpm lint` script won't ignore it, causing it to take forever to run.
=> chore(eslint): ignore .vscode-test folder

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json
- Prepare extension for 0.1.2 release. 
- Closes #337
=> chore: release TutorialKit vscode extension v0.1.2

docs/tutorialkit.dev/src/components/react-examples/ExampleFileTree.tsx, docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, docs/tutorialkit.dev/src/content/docs/reference/react-components.mdx, e2e/src/templates/default/file-on-template.js, e2e/src/templates/file-server/index.mjs, e2e/test/file-tree.test.ts, packages/react/src/Panels/WorkspacePanel.tsx, packages/react/src/core/ContextMenu.tsx, packages/runtime/src/store/index.ts, packages/runtime/src/store/tutorial-runner.ts, packages/types/src/default-localization.ts, packages/types/src/entities/index.ts, packages/types/src/schemas/i18n.ts
Show an error if user tries to create file that already exists on file system, but is not visible on FileTree. Such files are for example non-lesson template files.
=> fix: prevent overwriting template files via `<FileTree>`

docs/tutorialkit.dev/src/content/docs/reference/react-components.mdx
- Marks direct usage of `@tutorialkit/react` as experimental feature
- This does not affect users of TutorialKit. This affects only users who are using `@tutorialkit/react` without TutorialKit itself
The components of `@tutorialkit/react` are exposed as public API but we don't have any test cases for these components. We only have e2e tests through `@tutorialkit/astro`. When ever we implement new features to `@tutorialkit/astro`, we need to pay extra attention not to introduce any new required component props, or modify any existing ones to avoid semver breaking changes. Breaking the API is too easy at the moment and not easily visible from the code. 
Now that we are still in v0.x.x version, let's mark `@tutorialkit/react` API as experimental. This allows us to keep breaking the API when …
=> feat!: mark `@tutorialkit/react` component API as experimental feature

packages/runtime/src/utils/terminal.ts, packages/runtime/src/webcontainer/terminal-config.ts
- During https://github.com/stackblitz/tutorialkit/pull/348 it was noticed that `terminal.write` cannot be used to write into terminal's stdin. It's only useful for writing to stdout.
- Adds new terminal method that can be used to write commands to stdin. The #348 will add proper example into documentation.
```tsx
import tutorialStore from 'tutorialkit:store';
export default function Example() {
async function onClick() {
const terminal = tutorialStore.terminalConfig.value!.panels[0];
terminal.input('npm run test\n');
}
return (
<button
onClick={onClick}
className="px-4 py-1 my-3 cursor-pointer border-1 border-tk-border-primary rounded-md bg-tk-elements-primaryButton-backgroundColor text-tk-elements-primaryButton-textColor"
>
Run tests
</button>
);
}
```
=> feat(runtime): add `terminal.input` for writing to stdin

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx
**Description**
- Closes #207
- Adds docs for `components` and `defaultRoutes` in `@tutorialkit/astro`
=> docs: add docs for `defaultRoutes`

e2e/src/content/tutorial/tests/filesystem/meta.md, e2e/src/content/tutorial/tests/lesson-order/1-lesson/content.md, e2e/src/content/tutorial/tests/lesson-order/2-lesson/content.md, e2e/src/content/tutorial/tests/lesson-order/3-lesson/content.md, e2e/src/content/tutorial/tests/lesson-order/meta.md, e2e/test/lesson-order.test.ts, e2e/test/navigation.test.ts, e2e/test/terminal.test.ts
- Preparations for https://github.com/stackblitz/tutorialkit/issues/304
=> test(e2e): lessons ordering

packages/astro/src/default/utils/content.spec.ts
- Preparations for https://github.com/stackblitz/tutorialkit/issues/304
=> test: items excluded when not mentioned in order

docs/tutorialkit.dev/src/content/docs/guides/creating-content.mdx, docs/tutorialkit.dev/src/content/docs/reference/theming.mdx
**Description**
- Closes #250
- Adds docs for file imports using shortcuts `file` and `solution`
=> docs: add docs for file imports

docs/tutorialkit.dev/src/content/docs/guides/overriding-components.mdx, e2e/configs/override-components.ts, e2e/src/components/CustomHeadTags.astro, e2e/test/headtags.override-components.test.ts, packages/astro/package.json, packages/astro/src/default/components/HeadLinks.astro, packages/astro/src/default/components/HeadTags.astro, packages/astro/src/default/env-default.d.ts, packages/astro/src/default/layouts/Layout.astro, packages/astro/src/vite-plugins/override-components.ts, packages/cli/tests/__snapshots__/create-tutorial.test.ts.snap
I was investigating setting up a sitemap, using [@astrojs/sitemap](https://docs.astro.build/en/guides/integrations-guide/sitemap/).
For a proper setup, you also want to add a `link` tag in the page `head` to tell scrapers the URL to your sitemap (in addition to robot.txt). We could do this in the framework default setup, but that would mean setting up `sitemap` as an integration there and I'd rather give end users more control on the configuration.
So I went down the rabbit hole and implemented a replaceable `HeadTags` component.
I've tried to make the API as future proof as possible using slots.
=> feat(astro): override components to support `HeadTags`

packages/astro/src/vite-plugins/override-components.ts
- Related to https://github.com/stackblitz/tutorialkit/pull/375
All keys of `components` should be optional. 
```
18:30:26.671 | > astro check && astro build
18:30:26.671 |  
18:30:30.516 | ✘ [ERROR] The build was canceled
18:30:30.516 |  
18:30:30.519 | 15:30:30 [types] Generated 1.71s
18:30:30.526 | 15:30:30 [check] Getting diagnostics for Astro files in /opt/buildhome/repo...
18:30:32.992 | astro.config.ts:10:7 - error ts(2741): Property 'HeadTags' is missing in type '{ TopBar: string; }' but required in type 'OverrideComponentsOptions'.
18:30:32.993 |  
18:30:32.993 | 10       components: {
18:30:32.993 | ~~~~~~~~~~
18:30:32.993
```
=> fix(astro): types of override components to optional

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, e2e/src/components/CustomMetadata.astro, e2e/src/content/tutorial/tests/metadata/custom/content.mdx, e2e/src/content/tutorial/tests/metadata/meta.md, e2e/test/metadata.test.ts, packages/template/src/content/tutorial/1-basics/1-introduction/1-welcome/content.md, packages/types/src/entities/index.ts, packages/types/src/schemas/common.ts
All in the title:  a `custom` record on each configuration unlocks user-land features where we need to associate metadata to a specific entry:
- building a table of content
- building an RSS feed
- improved sitemap
- a tag system
- access extra meta information when crafting custom components : displaying the author name, publication date or such
It should be future proof in the sense that even if a feature is later brought to TutorialKit core, users will just remove their custom code when updating, but their app won't break.
Having it inherited could be relevant for some custom fields (author name), weird for others (publication date) : I feel that inheritance is still more convenient than setting custom fields on every tutorial? Also will inheritance proceed to a deep merge or not?
=> feat(astro): add `custom` configuration option for passing custom fields

.github/workflows/integration-test-cli.yaml, integration/cli/create-tutorial.test.ts, integration/package.json, integration/theme-resolving/inline-content.test.ts, packages/theme/package.json, packages/theme/src/index.spec.ts, packages/theme/src/index.ts, pnpm-lock.yaml
- Fixes https://github.com/stackblitz/tutorialkit/issues/382
Also adds test case that fails on Windows without the fix.
=> fix(theme): apply `fast-glob` Windows work-around for all `\@` matches

.github/workflows/integration-test-cli.yaml, packages/cli/package.json
=> chore: release CLI v1.1.1

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx
Based on the answer to issue #396 
https://github.com/stackblitz/tutorialkit/issues/396#issuecomment-2440130125
=> docs: add `previews: false` example

packages/react/src/Panels/EditorPanel.tsx, packages/react/src/core/FileTree.tsx
Small ui fix that adds `overflow-y: auto` to the editor file tree for when there are more files than fit in the editor panel
Before:
After:
=> fix(react): add vertical scroll bar to editor file tree

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/create-tutorial/CHANGELOG.md, packages/react/CHANGELOG.md, packages/react/package.json, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump core packages to version 1.2.0 and generate changelogs.
=> chore: release core packages v1.2.0

e2e/src/content/tutorial/tests/navigation/layout-change-all-off/content.md, e2e/src/content/tutorial/tests/navigation/meta.md, e2e/test/navigation.test.ts, packages/astro/src/default/pages/[...slug].astro, packages/react/src/Panels/PreviewPanel.tsx
=> fix: hide preview container when `previews: false`

docs/tutorialkit.dev/package.json, docs/tutorialkit.dev/src/content/docs/guides/overriding-components.mdx, docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, e2e/package.json, e2e/src/components/TopBar.astro, e2e/src/content/tutorial/meta.md, e2e/test/topbar.override-components.test.ts, e2e/test/topbar.test.ts, packages/astro/package.json, packages/astro/src/default/components/DownloadButton.tsx, packages/astro/src/default/components/TopBar.astro, packages/astro/src/default/components/TopBarWrapper.astro, packages/astro/src/default/pages/[...slug].astro, packages/astro/src/default/utils/__snapshots__/multiple-parts.json, packages/astro/src/default/utils/__snapshots__/single-lesson-no-part.json, packages/astro/src/default/utils/__snapshots__/single-part-and-lesson-no-chapter.json, packages/astro/src/default/utils/__snapshots__/single-part-chapter-and-lesson.json, packages/astro/src/default/utils/__snapshots__/single-part-chapter-and-multiple-lessons.json, packages/astro/src/default/utils/__snapshots__/single-part-multiple-chapters.json, packages/astro/src/default/utils/content.ts, packages/cli/overwrites/src/content/tutorial/meta.md, packages/cli/tests/__snapshots__/create-tutorial.test.ts.snap, packages/react/package.json, packages/runtime/package.json, packages/template/src/content/tutorial/1-basics/2-foo/meta.md, packages/template/src/content/tutorial/2-advanced/1-unicorn/meta.md, packages/template/src/content/tutorial/meta.md, packages/test-utils/package.json, packages/types/src/schemas/common.ts, pnpm-lock.yaml
- Closes https://github.com/stackblitz/tutorialkit/issues/166
=> feat(astro): add "Download lesson as zip" button

docs/tutorialkit.dev/src/content/docs/reference/configuration.mdx, packages/astro/src/default/components/MetaTags.astro, packages/astro/src/default/pages/index.astro, packages/types/src/schemas/metatags.ts
- Using URL in `meta.image` should work
https://github.com/AriPerkkio/tutorial-vite-plugin/pull/29
=> fix(astro): allow URLs in `meta.image`

packages/astro/src/default/components/MetaTags.astro
- Continues https://github.com/stackblitz/tutorialkit/pull/377
Currently used default `logo.svg` og-image does not show up in most social platforms. Let's use hosted `.png` one: `'https://tutorialkit.dev/tutorialkit-opengraph.png'`.
=> fix: switch default `meta.image` to `.png`

CHANGELOG.md, packages/astro/CHANGELOG.md, packages/astro/package.json, packages/cli/CHANGELOG.md, packages/create-tutorial/CHANGELOG.md, packages/react/CHANGELOG.md, packages/react/package.json, packages/runtime/CHANGELOG.md, packages/runtime/package.json, packages/theme/CHANGELOG.md, packages/theme/package.json, packages/types/CHANGELOG.md, packages/types/package.json
Bump core packages to version 1.3.1 and generate changelogs.
=> chore: release core packages v1.3.1

packages/astro/src/default/layouts/Layout.astro
I got deindexed by Google due to the lack of a proper canonical link, so here is a small update to set it up when the website has a configured absolute URL.
The PR just needs a double check because I was running the demo code which doesn't have an astro.config so no Astro.site.
Current palliative is to setup a custom HeadTags.
=> feat(astro): add sensible default canonical url

packages/astro/src/index.ts, packages/astro/src/integrations.ts
I would like to add custom expressive code plugins to change the way code blocks are rendered.
This PR adds an options `expressiveCodePlugins` property on the `tutorialkit` plugin that is instantiated in the `astro.config.ts`.
=> feat(astro): custom expressive code plugins

packages/astro/src/remark/import-file.ts
I would like to write an expressive code plugin that behaves differently for code blocks that were imported from the file system.  However, the import file logic removes all information about the file path before the expressive code plugins are called.
This change preserves that information so that expressive code plugins can access it.
=> feat(astro): preserve file path for imported file code blocks

packages/react/src/Panels/WorkspacePanel.tsx
My tutorial does not heavily use the preview panel, but always uses the terminal. This change allows the terminal to be open and the preview panel to be collapsed all the way (by the user).  The initial size of the preview panel stays the same.
=> fix(react): allow preview panel to be fully collapsed

packages/cli/src/commands/create/hosting-config/vercel.json
The generated `vercel.json` file content includes wrong headers, not matching the ones from the documentation:
- there is a typo for the first header
- the key of the second one is copied from the first one
=> fix: headers not matching the documentation

packages/astro/src/default/layouts/Layout.astro
Hey folks, long time no see!
After reviewing my sites SEO, I've noticed that the titles were not properly configured. Because TutorialKit also uses the title for navigation, it injects the chapter and part title too.
To sum it up the proposal
- if meta.title is set, use it in the `<title>` tag: it will be picked up by search engines. But also visible in the browser window, so we lose the display of the part and chapter.
- if not set, the `<title>` tag is just the navigational title `part / chapter /lesson`
Related but not included in this PR: I suspect `trailingSlash: "never"` is a reasonable default in the config, otherwise search engines might pick pages as duplicate. Might be worth an investigation.
=> fix: use `meta.title` as default `<title>`
