stackblitz/tutorialkit

- packages/cli/overwrites/src/content/tutorial/meta.md
> fix(cli): remove title from tutorial meta file

- .github/actions/setup-and-build/action.yml
This PR should fix the issue that popped up on CI.
> fix: update `pnpm/action-setup` to v4 to fix CI issue

- packages/cli/package.json
Bump TutorialKit CLI to version 0.0.3.
> chore: release TutorialKit CLI v0.0.3

- packages/template/.vscode/extensions.json
- Closes https://github.com/stackblitz/tutorialkit/issues/169
> feat(cli): add vs code extension to recommendations

- packages/cli/package.json
Bump TutorialKit CLI to version 0.1.1.
> chore: release TutorialKit CLI v0.1.1

- packages/cli/package.json
Bump TutorialKit CLI to version 0.1.2.
> chore: release TutorialKit CLI v0.1.2

- scripts/changelog.mjs
- Related to https://github.com/stackblitz/tutorialkit/actions/runs/10281471906/job/28451101036
- Broken in https://github.com/stackblitz/tutorialkit/pull/153
> chore: fix changelog generation

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/components/react/CHANGELOG.md
- packages/components/react/package.json
- packages/create-tutorial/CHANGELOG.md
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.1.3 and generate changelogs.
> chore: release core packages v0.1.3

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/components/react/CHANGELOG.md
- packages/components/react/package.json
- packages/create-tutorial/CHANGELOG.md
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.1.4 and generate changelogs.
> chore: release core packages v0.1.4

- packages/cli/package.json
> chore: release CLI v0.1.4

- packages/cli/package.json
> chore: release CLI v0.1.5

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/components/react/CHANGELOG.md
- packages/components/react/package.json
- packages/create-tutorial/CHANGELOG.md
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.1.6 and generate changelogs.
> chore: release core packages v0.1.6

- packages/cli/package.json
> chore: release CLI v0.1.6

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.2.0 and generate changelogs.
> chore: release core packages v0.2.0

- packages/cli/package.json
> chore: release CLI v0.2.0

- e2e/astro.config.ts
- Continues https://github.com/stackblitz/tutorialkit/pull/291
> test: remove `swap-functions` work-around

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.2.1 and generate changelogs.
> chore: release core packages v0.2.1

- packages/cli/package.json
> chore: release CLI v0.2.1

- docs/tutorialkit.dev/src/content/docs/guides/installation.mdx
Hey @AriPerkkio! Per a request from @EricSimons wanted to get something in about Enterprise Server into the docs here. Feel free to touch base with @Nemikolh if you have any questions on this.
-----
<a href="https://stackblitz.com/~/github.com/stackblitz/tutorialkit/tree/heygarrison/mention-enterprise-server"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/stackblitz/tutorialkit/tree/heygarrison/mention-enterprise-server)._
> chore: add info on Enterprise Server

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 0.2.2 and generate changelogs.
> chore: release core packages v0.2.2

- packages/create-tutorial/package.json
- packages/create-tutorial/scripts/build.js
- pnpm-lock.yaml
- Fixes https://github.com/stackblitz/tutorialkit/issues/308
> chore: windows local development fix

- packages/cli/package.json
> chore: release CLI v0.2.3

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.0.0 and generate changelogs.
> chore: release core packages v1.0.0

- packages/cli/package.json
> chore: release CLI v1.0.0

- docs/demo/src/content/tutorial/1-forms-css/2-colors/1-accent-color/content.md
While going through the demo, I came across a typo, so this is just a small PR to fix it 😄
> docs: typo in demo

- packages/astro/scripts/build.js
- packages/astro/src/default/utils/__snapshots__/multiple-parts.json
- packages/astro/src/default/utils/__snapshots__/single-part-chapter-and-lesson.json
- packages/astro/src/default/utils/__snapshots__/single-part-chapter-and-multiple-lessons.json
- packages/astro/src/default/utils/__snapshots__/single-part-multiple-chapters.json
- packages/astro/src/default/utils/content.spec.ts
- packages/astro/src/default/utils/content.ts
- Fixes error message when chapter is not found
Started to work on preparations for https://github.com/stackblitz/tutorialkit/issues/304 by creating test cases for current implementation of `getTutorial`. Noticed small bug while testing error messages. I'll be adding plenty of more test cases there later, but let's first fix this small bug.
> fix(astro): correct error message when chapter not found

- packages/astro/scripts/build.js
- Fixes dev mode that broke in https://github.com/stackblitz/tutorialkit/pull/361
> build: exclude snapshots from chokidar

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.1.0 and generate changelogs.
> chore: release core packages v1.1.0

- packages/cli/package.json
> chore: release CLI v1.1.0

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.1.1 and generate changelogs.
> chore: release core packages v1.1.1

- packages/cli/package.json
> chore: release CLI v1.2.0

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.2.1 and generate changelogs.
> chore: release core packages v1.2.1

- packages/cli/package.json
> chore: release CLI v1.2.1

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.2.2 and generate changelogs.
> chore: release core packages v1.2.2

- packages/cli/package.json
> chore: release CLI v1.2.2

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.3.0 and generate changelogs.
> chore: release core packages v1.3.0

- .github/workflows/publish-commit.yaml
- Trigger preview releases by PR tags instead of comments
> ci: preview releases by PR tags

- packages/cli/package.json
> chore: release CLI v1.3.1

- integration/package.json
- packages/astro/package.json
- packages/astro/src/default/utils/content.spec.ts
- packages/cli/package.json
- packages/react/package.json
- packages/runtime/package.json
- packages/test-utils/package.json
- packages/theme/package.json
- packages/types/package.json
- pnpm-lock.yaml
https://github.com/vitest-dev/vitest/releases/tag/v3.0.5
> chore(dev-deps): security patch to vitest

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.4.0 and generate changelogs.
> chore: release core packages v1.4.0

- packages/cli/package.json
> chore: release CLI v1.4.0

- e2e/test/topbar.test.ts
- Unblocks CI due to https://github.com/stackblitz/tutorialkit/issues/447
> test: disable "download as zip" tests for now

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.5.0 and generate changelogs.
> chore: release core packages v1.5.0

- packages/cli/package.json
> chore: release CLI v1.5.0

- e2e/test/topbar.test.ts
This reverts commit 1ca2f54f267dfdec7fa9f6329ef4dd3560ae8b4a.
> test: revert "test: disable "download as zip" tests for now (#448)"

- e2e/playwright.config.ts
- Makes testing in `webcontainer-ecosystem-ci` easier
> test(e2e): use list reporter

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.5.1 and generate changelogs.
> chore: release core packages v1.5.1

- packages/cli/package.json
> chore: release CLI v1.5.2

- CHANGELOG.md
- packages/astro/CHANGELOG.md
- packages/astro/package.json
- packages/cli/CHANGELOG.md
- packages/create-tutorial/CHANGELOG.md
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/runtime/CHANGELOG.md
- packages/runtime/package.json
- packages/theme/CHANGELOG.md
- packages/theme/package.json
- packages/types/CHANGELOG.md
- packages/types/package.json
Bump core packages to version 1.6.0 and generate changelogs.
> chore: release core packages v1.6.0

- packages/cli/package.json
> chore: release CLI v1.6.0
